### ISSUE TITLE
VCSA Permission

### ISSUE THREAD

**Issue by MaBauMeBad** [aleex42/vmware-vcsa-monitoring#1]
Hi,

i wanted to give your Scripts a shot and test them but ran into an error.

I want to run these script with a Serviceuser and not SSO Admin.
But without SSO Administrator Group Membership the Scripts are failing with Error `Not an ARRAY reference at ./check_vcsa_mem.pl line 72.`

Sample Command

`./check_vcsa_mem.pl --hostname VCSA --username monitoring@vsphere.local --password 'PASSWORD' --warning 80 --critical 90`

If i try the same command with SSO Administrator credentials or a serviceuser with SSO Administrator Groupmembership it works.

Can you may help me to specify wich permissions are necessary for the Scripts ?

We are currently on vCenter 6.7.0 Build  16046713

Thank you very much

**Comment by aleex42** [comment]
I‘m Not sure which Account i‘ve used.

Did you Try Root for testing?

Von meinem iPhone gesendet

**Comment by MaBauMeBad** [comment]
Hi Alex,

thanks for your fast respone.
According to your samples you used the SSO administrator (administrator@vsphere.local)

root user is not working. I tried it also with SSO and Active-Directory Users.
Same result for all. As long the User is not in the Administrator Group of the SSO Domain, the Error above shows up - even if i give full accsess via vCenter Root Level or Global Permissions to the Users

**Comment by aleex42** [comment]
Yes, I'm getting the same error. Seems like a ssl verfication stuff ...

```
                                    '_msg' => 'Can\'t connect to vcenter.xxx:443 (certificate verify failed)',

                                    '_content' => 'Can\'t connect to vcenter.xxx:443 (certificate verify failed)

SSL connect attempt failed error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed at /usr/share/perl5/LWP/Protocol/http.pm line 50.
'
                                  }, 'HTTP::Response' )
```

**Comment by aleex42** [comment]
Was fixed in commit 2609cef - please try again :-)

**Comment by MaBauMeBad** [comment]
Good Morning Alex,

sorry for the late respone.
Thanks for your fix, but it isnt fixing the Permission "Problem".

For me its stille the case that a Serviceaccount needs to be member of the SSO Administrator Group.
I'm not even sure if it is a Problem or just by VMware Design that only an SSO Administrator can accsess the API - even for Read-Only.
I was trying to figure that out, but didnt find yet the right information.

Do you have any input there ? I can not imagine that a "simple" Monitoring Script needs Full Admin Permission.

If your curious i can show you live what happen on my site.

Thanks ;)

**Comment by aleex42** [comment]
Ah I understand. I will try that ... currently I can confirm, that a readonly account won't be enough ...

**Comment by MaBauMeBad** [comment]
Hi Alex,

did you made any progress ?
