### ISSUE TITLE
Malformed JSON error

### ISSUE THREAD

**Issue by Optimaximal** [aleex42/vmware-vcsa-monitoring#2]
Hi,

I've tried to deploy your perl scripts to Icinga2, but when I execute them from the CLI, I get the following:

```
/usr/lib/nagios/plugins# ./check_vcsa_storage.pl --hostname vcentre.XXX --username XXX --password XXX --warning 10 --critical 5
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "LWP will support htt...") at ./check_vcsa_storage.pl line 63.
```
```
/usr/lib/nagios/plugins# ./check_vcsa_cpu.pl --hostname vcentre.XXX --username XXX --password XXX --warning 10 --critical 5
malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "LWP will support htt...") at ./check_vcsa_cpu.pl line 58.
```

This is attempting to check a VCSA running v6.7.0.40000.

Any ideas?

**Comment by aleex42** [comment]
First idea: sounds like login didn’t work ...

**Comment by Optimaximal** [comment]
The credentials are correct and I've also tried it using other known working logins on both the vsphere.local domain and our AD domain with users who have Administrator roles on the server.

Do you know if I have to enable something on vSphere to allow the queries?
Are there any pre-requisites I'm missing? I did have to install libjson-perl via apt-get and also had to manually download Client.pm from [here](https://metacpan.org/source/KKANE/REST-Client-273/lib/REST/Client.pm) (correct version?) to /etc/perl/REST.
Is there a way to modify one of the scripts to actually output the json? I don't know PERL...

**Comment by Optimaximal** [comment]
Ahha, I just logged into vSphere and there was the following error message in the bottom right of the UI...

`ResponseError Unauthorized, status: 401, message: Http failure response for https://vcentre.footshopltd.co.uk/rest/vcenter/topology/nodes: 401 Unauthorized, url: https://vcentre.footshopltd.co.uk/rest/vcenter/topology/nodes`

Have I just not enabled something?

**Comment by aleex42** [comment]
In the CPU script, insert after this line:

`my $response = $ua->request($request);
`

this code:

`use Data::Dumper;`
`print Dumper($response);`

That should give you the full output of the API call including errors etc.

**Comment by Optimaximal** [comment]
Ok, this returned...

```
$VAR1 = bless( {
                 '_rc' => 501,
                 '_msg' => 'Protocol scheme \'https\' is not supported (LWP::Protocol::https not installed)',
                 '_headers' => bless( {
                                        'content-type' => 'text/plain',
                                        '::std_case' => {
                                                          'client-warning' => 'Client-Warning',
                                                          'client-date' => 'Client-Date'
                                                        },
                                        'client-date' => 'Mon, 19 Oct 2020 09:34:17 GMT',
                                        'client-warning' => 'Internal response'
                                      }, 'HTTP::Headers' ),
                 '_content' => 'LWP will support https URLs if the LWP::Protocol::https module
is installed.
',
                 '_request' => bless( {
                                        '_headers' => bless( {
                                                               'content-type' => 'application/x-www-form-urlencoded',
                                                               'content-length' => 0,
                                                               'user-agent' => 'libwww-perl/6.31',
                                                               'authorization' => 'Basic YWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2FsOmYwMHQrd2Vhcg=='
                                                             }, 'HTTP::Headers' ),
                                        '_uri' => bless( do{\(my $o = 'https://vcentre.footshopltd.co.uk/rest/com/vmware/cis/session')}, 'URI::https' ),
                                        '_method' => 'POST',
                                        '_content' => ''
                                      }, 'HTTP::Request' )
               }, 'HTTP::Response' );
```

A quick google landed me here - https://stackoverflow.com/questions/19009374/installing-perl-module-lwpprotocolhttps.  Ran the following and the error has gone...

`apt-get install libcrypt-ssleay-perl`

Now, though, check_vcsa_services.pl is working fine, but the others all fail with a `Not an ARRAY reference` error.

```
./check_vcsa_storage.pl --hostname vcentre.XXX --username XXX --password XXX --warning 10 --critical 5
Not an ARRAY reference at ./check_vcsa_storage.pl line 92.
./check_vcsa_mem.pl --hostname vcentre.XXX --username XXX --password XXX --warning 10 --critical 5
Not an ARRAY reference at ./check_vcsa_mem.pl line 73.
./check_vcsa_cpu.pl --hostname vcentre.XXX --username XXX --password XXX --warning 10 --critical 5
Not an ARRAY reference at ./check_vcsa_cpu.pl line 76.
```
Dug into it further, moving the dumper after the decode of the response the and I'm getting the following. Clearly something is blocking the transmission of the authentication details...
```
$VAR1 = {
          'value' => {
                       'messages' => [
                                       {
                                         'id' => 'vapi.method.authentication.required',
                                         'args' => [],
                                         'default_message' => 'This method requires authentication.'
                                       }
                                     ]
                     },
          'type' => 'com.vmware.vapi.std.errors.unauthenticated'
        };
```

🤷‍♂️

**Comment by aleex42** [comment]
'_content' => '{"type":"com.vmware.vapi.std.errors.unauthorized","value":{"error_type":"UNAUTHORIZED","messages":[{"args":[],"default_message":"Unable to authorize user","id":"vapi.security.authorization.invalid"}]}}',

Hm. I can confirm that ...

**Comment by aleex42** [comment]
And no.

Using “administrator@vsphere.local <mailto:administrator@vsphere.local>” CPU is working for me:

                                    '_content' => '{"value":[{"start_time":"2020-10-19T09:52:58.000Z","data":["44.218478003640165","37.21367334970269"],"function":"MAX","name":"cpu.util","end_time":"2020-10-19T09:56:18.000Z","interval":"MINUTES5"}]}',

**Comment by Optimaximal** [comment]
Which VCSA version are you using? We're on 6.7.0.40000, which is about 10 versions out of date. I'll attempt an update, which won't be today whilst i'm working remotely.

I have restarted the Appliance Management service, as indicated [here](https://kb.vmware.com/s/article/67483) but it's not made a difference.

**Comment by aleex42** [comment]
Hello,

Version:
7.0.0.10100
Build number
15952498

But it was working with 6.7, too.

Have no 6.7 vCenter here for debugging now :-(

Regards,
Alex

**Comment by Optimaximal** [comment]
I'm going to update to latest release of 6.7 then try again.

**Comment by aleex42** [comment]
Okay, otherwise we can start a debugging session together :-)

**Comment by Optimaximal** [comment]
Updating to the latest 6.7 didn't fix it, but out of the blue I tried enabling the BASH Shell Access on the server in the VSAM and now CPU & Storage are working!

Mem still throws the following error:
```
Argument "" isn't numeric in sprintf at ./check_vcsa_mem.pl line 74.
OK: Memory Usage 0.00 %
```
line: `$memory_percent = sprintf("%.2f", $memory_percent);`

Can I also suggest providing a list of requirements and prerequisites for using these plugins (i.e. enable bash, list of specific PERL modules etc)?

I had to install the following to an Ubuntu 18.04 instance to get these scripts working:

- libcrypt-ssleay-perl
- libjson-perl
- Download Client.pm from [here](https://metacpan.org/source/KKANE/REST-Client-273/lib/REST/Client.pm) to /etc/perl/REST/ and make executable with chmod

**Comment by aleex42** [comment]
Can you send the debug from MEM?

I’m using these plugins with debian, there I have installed "librest-client-perl”

I will write these requirements to the page :)

**Comment by Optimaximal** [comment]
Which value would you like me to dump? $memory_percent?

**Comment by aleex42** [comment]
No, just $response as before :-)

**Comment by Optimaximal** [comment]
Oh, I think I see what's happening. Your plugin collects the results per minute for the last 5 minutes. Until 5 values are available, it's returning empty strings, which you're trying to convert to integers with decimal places, hence the error.

It's working fine now there are 5 values...

**Comment by aleex42** [comment]
Okay. So waiting a few minutes until all values are there, then problem fixed? :-)

All problems fixed now?

**Comment by Optimaximal** [comment]
Yes, it's working.
